In [1]:
#importing all required packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
#train file
df= pd.read_csv("/content/mergedtrain.csv")
df.head()

,id,week,center_id,meal_id,checkout_price,base_price,emailer_for_promotion,homepage_featured,num_orders,category,cuisine,city_code,region_code,center_type,op_area
0,1379560,1,55,1885,136.83,152.29,0,0,177,Beverages,Thai,647,56,TYPE_C,2.0
1,1018704,2,55,1885,135.83,152.29,0,0,323,Beverages,Thai,647,56,TYPE_C,2.0
2,1196273,3,55,1885,132.92,133.92,0,0,96,Beverages,Thai,647,56,TYPE_C,2.0
3,1116527,4,55,1885,135.86,134.86,0,0,163,Beverages,Thai,647,56,TYPE_C,2.0
4,1343872,5,55,1885,146.50,147.50,0,0,215,Beverages,Thai,647,56,TYPE_C,2.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 456548 entries, 0 to 456547
Data columns (total 15 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   id                     456548 non-null  int64
 1   week                   456548 non-null  int64
 2   center_id              456548 non-null  int64
 3   meal_id                456548 non-null  int64
 4   checkout_price         456548 non-null  float64
 5   base_price             456548 non-null  float64
 6   emailer_for_promotion  456548 non-null  int64
 7   homepage_featured      456548 non-null  int64
 8   num_orders             456548 non-null  int64
 9   category               456548 non-null  object
 10  cuisine                456548 non-null  object
 11  city_code              456548 non-null  int64
 12  region_code            456548 non-null  int64
 13  center_type            456548 non-null  object
 14  op_area                456548 non-null  float64
dtypes: float64(3), int64(9), object(3)
memory usage: 52.2+ MB

In [5]:
df.nunique()

id                       456548
week                        145
center_id                    77
meal_id                      51
checkout_price             1992
base_price                 1907
emailer_for_promotion         2
homepage_featured             2
num_orders                 1250
category                     14
cuisine                       4
city_code                    51
region_code                   8
center_type                   3
op_area                      30
dtype: int64

In [6]:
df['id'].duplicated().sum()

0

**feature engineering**

In [7]:
train_df=df.copy()

In [8]:
#Seperating the target feature

X_train = train_df.drop(columns=['num_orders'])
y_train = train_df['num_orders']

In [9]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 456548 entries, 0 to 456547
Data columns (total 14 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   id                     456548 non-null  int64
 1   week                   456548 non-null  int64
 2   center_id              456548 non-null  int64
 3   meal_id                456548 non-null  int64
 4   checkout_price         456548 non-null  float64
 5   base_price             456548 non-null  float64
 6   emailer_for_promotion  456548 non-null  int64
 7   homepage_featured      456548 non-null  int64
 8   category               456548 non-null  object
 9   cuisine                456548 non-null  object
 10  city_code              456548 non-null  int64
 11  region_code            456548 non-null  int64
 12  center_type            456548 non-null  object
 13  op_area                456548 non-null  float64
dtypes: float64(3), int64(8), object(3)
memory usage: 48.8+ MB

In [10]:
print(X_train.columns)

Index(['id', 'week', 'center_id', 'meal_id', 'checkout_price', 'base_price',
       'emailer_for_promotion', 'homepage_featured', 'category', 'cuisine',
       'city_code', 'region_code', 'center_type', 'op_area'],
      dtype='object')

In [11]:
# Verify train_df columns
print("Columns in train_df:", train_df.columns)

# Verify X_train columns
print("Columns in X_train:", X_train.columns)

# Ensure 'meal_id' is present and aligns
if 'meal_id' in train_df.columns:
    print("meal_id exists in train_df")

if 'meal_id' in X_train.columns:
    print("meal_id exists in X_train")
else:
    print("meal_id missing in X_train")

Columns in train_df: Index(['id', 'week', 'center_id', 'meal_id', 'checkout_price', 'base_price',
       'emailer_for_promotion', 'homepage_featured', 'num_orders', 'category',
       'cuisine', 'city_code', 'region_code', 'center_type', 'op_area'],
      dtype='object')
Columns in X_train: Index(['id', 'week', 'center_id', 'meal_id', 'checkout_price', 'base_price',
       'emailer_for_promotion', 'homepage_featured', 'category', 'cuisine',
       'city_code', 'region_code', 'center_type', 'op_area'],
      dtype='object')
meal_id exists in train_df
meal_id exists in X_train

In [12]:
print(train_df.index)
print(X_train.index)

RangeIndex(start=0, stop=456548, step=1)
RangeIndex(start=0, stop=456548, step=1)

In [13]:
# Create rolling mean features for num_orders

# Sample data (assuming train_df and X_train are already defined)
# Ensure 'meal_id' is present in both DataFrames
if 'meal_id' in train_df.columns and 'meal_id' in X_train.columns:
    # Compute rolling means for num_orders
    rolling_mean_3 = train_df.groupby('meal_id')['num_orders'].rolling(3).mean().reset_index(level=0, drop=True).fillna(0)
    rolling_mean_7 = train_df.groupby('meal_id')['num_orders'].rolling(7).mean().reset_index(level=0, drop=True).fillna(0)

    # Add rolling mean features to X_train
    X_train['num_orders_rolling_mean_3'] = rolling_mean_3
    X_train['num_orders_rolling_mean_7'] = rolling_mean_7

    # Fill any remaining NaN values
    X_train['num_orders_rolling_mean_3'].fillna(0, inplace=True)
    X_train['num_orders_rolling_mean_7'].fillna(0, inplace=True)
else:
    print("Error: 'meal_id' column is not present in one of the DataFrames")

In [14]:
# Create features for the difference between base price and checkout price
X_train['price_diff'] = X_train['base_price'] - X_train['checkout_price']

# Create features for the ratio of base price to checkout price
X_train['price_ratio'] = X_train['base_price'] / X_train['checkout_price']

# Create features for the interaction between emailer_for_promotion and homepage_featured
X_train['promotion_interaction'] = X_train['emailer_for_promotion'] + X_train['homepage_featured']

# One-hot encode categorical features
# Convert categorical features to numerical using one-hot encoding
X_train = pd.get_dummies(X_train, columns=['category', 'cuisine', 'city_code', 'region_code', 'center_type'])

In [15]:
# Create lagged features for num_orders
X_train['num_orders_lag1'] = train_df.groupby(['meal_id'])['num_orders'].shift(1).fillna(0)
X_train['num_orders_lag2'] = train_df.groupby(['meal_id'])['num_orders'].shift(2).fillna(0)

In [16]:
import datetime

# Create features for the day of the week and month
# Assuming 'week' is in the format 'YYYY-WW' (year and week number)
# If 'week' is an integer, convert it to string first and pad with zeros if necessary
X_train['week'] = X_train['week'].astype(str).apply(lambda x: x.zfill(2)) # Pad with zeros if week number is single digit
X_train['week'] = X_train['week'].apply(lambda x: '2018-' + x) # Assuming all data is from 2018, replace with actual year if different

# Handle weeks beyond 53 and potential multiple hyphens
def handle_week(week_str):
    parts = week_str.split('-')  # Split by hyphen
    if len(parts) == 2:  # Handle the standard case with two parts
        year, week_num = parts
        if int(week_num) > 53:
            year = str(int(year) + 1)
            week_num = '01'  # Start with week 1 of the next year
        return datetime.datetime.strptime(year + '-'+ week_num + '-1', "%Y-%W-%w")
    else:  # Handle cases with multiple hyphens
        # Implement logic to extract year and week number for these cases
        # For example, you might take the first and last parts as year and week number
        return datetime.datetime(2018, 1, 1)  # Return a default date instead of None

X_train['week'] = X_train['week'].apply(handle_week)

# Check if 'week' column contains datetime objects
print(X_train['week'].dtype)

# If not datetime, convert to datetime
if X_train['week'].dtype != 'datetime64[ns]':
    X_train['week'] = pd.to_datetime(X_train['week'])

X_train['day_of_week'] = X_train['week'].dt.dayofweek
X_train['month'] = X_train['week'].dt.month

# Create features for the number of orders per center per week
center_week_count = X_train.groupby(["center_id", "week"])["id"].count().reset_index()
center_week_count.columns = ["center_id", "week", "center_week_count"]
X_train = pd.merge(X_train, center_week_count, on=["center_id", "week"], how="left")

# Find the one-hot encoded category columns
category_columns = [col for col in X_train.columns if col.startswith('category_')]

# Iterate over one-hot encoded category columns and create features
for category_col in category_columns:
    category_week_count = X_train.groupby([category_col, "week"])["id"].count().reset_index()
    category_week_count.columns = [category_col, "week", category_col + "_week_count"]
    X_train = pd.merge(X_train, category_week_count, on=[category_col, "week"], how="left")

# Create features for the average number of orders per meal in the last 4, 10 and 20 weeks
X_train['meal_avg_orders_4w'] = train_df.groupby('meal_id')['num_orders'].transform(lambda x: x.rolling(4).mean().shift(1))
X_train['meal_avg_orders_10w'] = train_df.groupby('meal_id')['num_orders'].transform(lambda x: x.rolling(10).mean().shift(1))
X_train['meal_avg_orders_20w'] = train_df.groupby('meal_id')['num_orders'].transform(lambda x: x.rolling(20).mean().shift(1))

# Create features for the average price difference per meal in the last 4, 10 and 20 weeks
X_train['meal_avg_price_diff_4w'] = X_train.groupby('meal_id')['price_diff'].transform(lambda x: x.rolling(4).mean().shift(1))
X_train['meal_avg_price_diff_10w'] = X_train.groupby('meal_id')['price_diff'].transform(lambda x: x.rolling(10).mean().shift(1))
X_train['meal_avg_price_diff_20w'] = X_train.groupby('meal_id')['price_diff'].transform(lambda x: x.rolling(20).mean().shift(1))

# Fill missing values in newly created features
X_train.fillna(0, inplace=True)

datetime64[ns]

In [23]:
X_train.head()

,id,week,center_id,meal_id,checkout_price,base_price,emailer_for_promotion,homepage_featured,op_area,num_orders_rolling_mean_3,...,category_Rice Bowl_week_count,category_Salad_week_count,category_Sandwich_week_count,category_Seafood_week_count,category_Soup_week_count,category_Starters_week_count,meal_avg_orders_3w,meal_avg_orders_7w,meal_avg_price_diff_3w,meal_avg_price_diff_7w
0,1379560,2018-01-01,55,1885,136.83,152.29,0,0,2.0,0.000000,...,2691,2922,2692,2756,2843,2713,0.00,0.0,0.00,0.0
1,1018704,2018-01-08,55,1885,135.83,152.29,0,0,2.0,0.000000,...,2666,2896,2667,2728,2814,2685,0.00,0.0,0.00,0.0
2,1196273,2018-01-15,55,1885,132.92,133.92,0,0,2.0,198.666667,...,2668,2899,2669,2732,2817,2691,0.00,0.0,0.00,0.0
3,1116527,2018-01-22,55,1885,135.86,134.86,0,0,2.0,194.000000,...,2658,2889,2659,2719,2804,2675,0.00,0.0,0.00,0.0
4,1343872,2018-01-29,55,1885,146.50,147.50,0,0,2.0,158.000000,...,2631,2859,2632,2670,2780,2650,189.75,0.0,7.98,0.0

In [24]:
X = X_train.copy()
y = y_train.copy()

**Splitting**

In [25]:
#splitting the data first into two part -- doing a 70:30 split i.e 30% data fed to intermediate test data set

from sklearn.model_selection import train_test_split
x_train1,x_test,y_train1,y_test = train_test_split(X,y,test_size=0.3,random_state=0 )

In [26]:
x_train1.shape ,x_test.shape ,y_train1.shape , y_test.shape

((319583, 117), (136965, 117), (319583,), (136965,))

In [28]:
# **XGBoost**

import xgboost as xgb
import pandas as pd

# Convert 'week' column to numerical representation (e.g., ordinal)
# Assuming 'week' represents a week number within a year
x_train1['week'] = x_train1['week'].dt.isocalendar().week
x_test['week'] = x_test['week'].dt.isocalendar().week

# Create XGBoost regressor object
xgb_model = xgb.XGBRegressor(
    n_estimators=100,  # Number of boosting rounds
    learning_rate=0.1,  # Step size shrinkage used in update to prevent overfitting
    max_depth=10,  # Maximum depth of a tree
    subsample=0.8,  # Subsample ratio of the training instances
    colsample_bytree=0.8,  # Subsample ratio of columns when constructing each tree
    random_state=42  # Random number seed for reproducibility
)

# Fit the model to the training data
xgb_model.fit(x_train1, y_train1)

# Make predictions on the test data
xgb_preds = xgb_model.predict(x_test)

# **Evaluation**
from sklearn.metrics import mean_squared_error

# Calculate RMSE for XGBoost
xgb_rmse = np.sqrt(mean_squared_error(y_test, xgb_preds)) # Fixed variable name here from xgb_predictions to xgb_preds
print("XGBoost RMSE:", xgb_rmse)

import numpy as np
from sklearn.metrics import mean_squared_log_error

def rmsle(y_true, y_pred):
  """
  Calculates the Root Mean Squared Logarithmic Error (RMSLE)

  Args:
    y_true: Array-like, true target values.
    y_pred: Array-like, predicted target values.

  Returns:
    The RMSLE score.
  """
  y_true_clipped = np.clip(y_true, a_min=0, a_max=None)
  y_pred_clipped = np.clip(y_pred, a_min=0, a_max=None)
  return np.sqrt(mean_squared_log_error(y_true_clipped, y_pred_clipped))

# Example usage (assuming y_test and xgb_preds are defined):
rmsle_score = rmsle(y_test, xgb_preds)
print("RMSLE:", rmsle_score)

from sklearn.metrics import mean_squared_log_error
xgb_rmsle = rmsle(y_test, xgb_preds)
print("XGBoost RMSLE:", xgb_rmsle)

XGBoost RMSE: 63.86542621363705
RMSLE: 0.1466055601676187
XGBoost RMSLE: 0.1466055601676187

In [32]:
import lightgbm as lgb
import numpy as np

def rmsle(preds, data):
    """ Root Mean Squared Logarithmic Error """
    labels = data.get_label()
    preds = np.maximum(0, preds)  # Ensure there are no negative values
    rmsle_value = np.sqrt(np.mean((np.log1p(preds) - np.log1p(labels))**2))
    return 'rmsle', rmsle_value, False

# Assuming X_train, y_train, X_test, y_test are already defined

# Create LightGBM datasets
train_data = lgb.Dataset(x_train1, label=y_train1)
valid_data = lgb.Dataset(x_test, label=y_test, reference=train_data)

# Define the parameters
params = {
    'objective': 'regression',
    'metric': 'rmse',
    'boosting_type': 'gbdt',
    'learning_rate': 0.05,
    'num_leaves': 31,
    'verbose': -1
}

# Train the LightGBM model with early stopping and custom metric
lgb_model = lgb.train(
    params,
    train_data,
    num_boost_round=1000,
    valid_sets=[train_data, valid_data],
    valid_names=['train', 'valid'],
    feval=rmsle,
    callbacks=[lgb.early_stopping(stopping_rounds=10)]
)

# Predict using the trained model
y_pred = lgb_model.predict(x_test, num_iteration=lgb_model.best_iteration)

Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[870]	train's rmse: 24.8349	train's rmsle: 0.135514	valid's rmse: 57.0596	valid's rmsle: 0.139313

In [17]:
#maintestfile

test_df1= pd.read_csv("/content/test.csv")
test_df1.head()

,id,week,center_id,meal_id,checkout_price,base_price,emailer_for_promotion,homepage_featured
0,1028232,146,55,1885,158.11,159.11,0,0
1,1127204,146,55,1993,160.11,159.11,0,0
2,1212707,146,55,2539,157.14,159.14,0,0
3,1082698,146,55,2631,162.02,162.02,0,0
4,1400926,146,55,1248,163.93,163.93,0,0

In [18]:
df2= pd.read_csv("/content/meal_info.csv")
df2.head()

   meal_id   category cuisine
0     1885  Beverages    Thai
1     1993  Beverages    Thai
2     2539  Beverages    Thai
3     1248  Beverages  Indian
4     2631  Beverages  Indian

In [19]:
df3= pd.read_csv("/content/fulfilment_center_info.csv")
df3.head()

   center_id  city_code  region_code center_type  op_area
0         11        679           56      TYPE_A      3.7
1         13        590           56      TYPE_B      6.7
2        124        590           56      TYPE_C      4.0
3         66        648           34      TYPE_A      4.1
4         94        632           34      TYPE_C      3.6

In [20]:
test_df2 = pd.merge(test_df1, df2 , on='meal_id')
test_df = pd.merge(test_df2, df3 , on='center_id')

test_df.head()

,id,week,center_id,meal_id,checkout_price,base_price,emailer_for_promotion,homepage_featured,category,cuisine,city_code,region_code,center_type,op_area
0,1028232,146,55,1885,158.11,159.11,0,0,Beverages,Thai,647,56,TYPE_C,2.0
1,1262649,147,55,1885,159.11,159.11,0,0,Beverages,Thai,647,56,TYPE_C,2.0
2,1453211,149,55,1885,157.14,158.14,0,0,Beverages,Thai,647,56,TYPE_C,2.0
3,1262599,150,55,1885,159.14,157.14,0,0,Beverages,Thai,647,56,TYPE_C,2.0
4,1495848,151,55,1885,160.11,159.11,0,0,Beverages,Thai,647,56,TYPE_C,2.0

In [33]:
final_test = test_df.copy()

In [35]:
# Create features for the difference between base price and checkout price
final_test['price_diff'] = final_test['base_price'] - final_test['checkout_price']

# Create features for the ratio of base price to checkout price
final_test['price_ratio'] = final_test['base_price'] / final_test['checkout_price']

# Create features for the interaction between emailer_for_promotion and homepage_featured
final_test['promotion_interaction'] = final_test['emailer_for_promotion'] * final_test['homepage_featured']

# One-hot encode categorical features
# Convert categorical features to numerical using one-hot encoding
final_test = pd.get_dummies(final_test, columns=['category', 'cuisine', 'city_code', 'region_code', 'center_type'])

In [36]:
# Create rolling mean features for num_orders (using a placeholder since num_orders is not available in test data)
final_test['num_orders_rolling_mean_3'] = 0  # Placeholder, cannot calculate without target variable
final_test['num_orders_rolling_mean_7'] = 0  # Placeholder

# Create lagged features for num_orders (using placeholder values)
final_test['num_orders_lag1'] = 0  # Placeholder, cannot calculate without historical data
final_test['num_orders_lag2'] = 0  # Placeholder

In [37]:
# prompt: Engineer the same features generated in X_train for X_test
import datetime

# Create features for the day of the week and month
# Assuming 'week' is in the format 'YYYY-WW' (year and week number)
final_test['week'] = final_test['week'].astype(str).apply(lambda x: x.zfill(2))
final_test['week'] = final_test['week'].apply(lambda x: '2018-' + x)  # Assuming all data is from 2018

# Handle weeks beyond 53 and potential multiple hyphens
final_test['week'] = final_test['week'].apply(handle_week)  # Using the same function defined earlier

# Check if 'week' column contains datetime objects
print(final_test['week'].dtype)

# If not datetime, convert to datetime
if final_test['week'].dtype != 'datetime64[ns]':
    final_test['week'] = pd.to_datetime(X_test['week'])

final_test['day_of_week'] = final_test['week'].dt.dayofweek
final_test['month'] = final_test['week'].dt.month

# Create features for the number of orders per center per week
center_week_count_test = final_test.groupby(["center_id", "week"])["id"].count().reset_index()
center_week_count_test.columns = ["center_id", "week", "center_week_count"]
final_test = pd.merge(final_test, center_week_count_test, on=["center_id", "week"], how="left")

# Find the one-hot encoded category columns
category_columns_test = [col for col in final_test.columns if col.startswith('category_')]

# Iterate over one-hot encoded category columns and create features
for category_col in category_columns_test:
    category_week_count = final_test.groupby([category_col, "week"])["id"].count().reset_index()
    category_week_count.columns = [category_col, "week", category_col + "_week_count"]
    final_test = pd.merge(final_test, category_week_count, on=[category_col, "week"], how="left")

# Create features for the average number of orders per meal in the last 4,10 and 20 weeks (placeholders)
final_test['meal_avg_orders_4w'] = 0  # Placeholder, cannot calculate without historical data
final_test['meal_avg_orders_10w'] = 0  # Placeholder
final_test['meal_avg_orders_20w'] = 0  # Placeholder

# Create features for the average price difference per meal in the last 4,10 and 20 weeks (placeholders)
final_test['meal_avg_price_diff_4w'] = 0  # Placeholder, cannot calculate without historical data
final_test['meal_avg_price_diff_10w'] = 0  # Placeholder
final_test['meal_avg_price_diff_20w'] = 0  # Placeholder

# Fill missing values in newly created features
final_test.fillna(0, inplace=True)

datetime64[ns]

In [38]:
final_test.head()

,id,week,center_id,meal_id,checkout_price,base_price,emailer_for_promotion,homepage_featured,op_area,price_diff,...,category_Rice Bowl_week_count,category_Salad_week_count,category_Sandwich_week_count,category_Seafood_week_count,category_Soup_week_count,category_Starters_week_count,meal_avg_orders_3w,meal_avg_orders_7w,meal_avg_price_diff_3w,meal_avg_price_diff_7w
0,1028232,2019-01-07,55,1885,158.11,159.11,0,0,2.0,1.0,...,30264,30264,30265,30876,31608,30589,0,0,0,0
1,1262649,2019-01-07,55,1885,159.11,159.11,0,0,2.0,0.0,...,30264,30264,30265,30876,31608,30589,0,0,0,0
2,1453211,2019-01-07,55,1885,157.14,158.14,0,0,2.0,1.0,...,30264,30264,30265,30876,31608,30589,0,0,0,0
3,1262599,2019-01-07,55,1885,159.14,157.14,0,0,2.0,-2.0,...,30264,30264,30265,30876,31608,30589,0,0,0,0
4,1495848,2019-01-07,55,1885,160.11,159.11,0,0,2.0,-1.0,...,30264,30264,30265,30876,31608,30589,0,0,0,0

In [39]:
final_test.shape

(32573, 117)

In [40]:
# prompt: use lightgbm to predict the num_orders column for final_test dataset

# Assuming 'final_test' is the DataFrame containing the test data
# and 'lgb_model' is the trained LightGBM model

# Convert 'week' column to numerical representation (e.g., ordinal)
final_test['week'] = final_test['week'].dt.isocalendar().week

# Make predictions on the test data
final_predictions = lgb_model.predict(final_test, num_iteration=lgb_model.best_iteration)

# Create a DataFrame for submission
submission_df = pd.DataFrame({
    'id': final_test['id'],
    'num_orders': final_predictions
})

# Ensure predictions are non-negative
submission_df['num_orders'] = submission_df['num_orders'].clip(lower=0)

# Save the submission file
submission_df.to_csv('submission.csv', index=False)

# **Next Steps:**


**Hyperparameter Tuning and Cross-Validation**

*   Use techniques like GridSearchCV or RandomizedSearchCV to find optimal hyperparameters for both models.

*   Implement cross-validation to get a more robust estimate of model performance especially in XGBoost.(Validated data for LightGBM).


**Further Improvements**

*   Feature Engineeering: Explore additional features that might improve the models.

*   Feature Selection: Find a technique (Catboost has been used for this, may explore other techniques) to extract the features that really matters and use only those features to avoid overfitting of train datasets.

*   
Model stacking: Combine predictions from multiple models to potentially improve accuracy.

*   Check for Outliers to see if there is a need to standardize/normalize the datasets.